/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Portao.JanelaGUI;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Joamila
 * Criado em: 18/04/2016
 * Última atualização em: 20/04/2016
 */
public class PortaoGUI extends javax.swing.JFrame {

    /**
     * Creates new form PortaoGUI
     */
    public PortaoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        janelaPanel = new javax.swing.JPanel();
        contadorPanel = new javax.swing.JPanel();
        milharContLabel = new javax.swing.JLabel();
        centenaContLabel = new javax.swing.JLabel();
        dezenaContLabel = new javax.swing.JLabel();
        unidadeContLabel = new javax.swing.JLabel();
        catracaPanel = new javax.swing.JPanel();
        catracaLabel = new javax.swing.JLabel();
        entrarButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Portão - by Joamila");
        setBounds(new java.awt.Rectangle(0, 0, 300, 405));
        setPreferredSize(new java.awt.Dimension(300, 405));
        setResizable(false);

        milharContLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Portao/JanelaGUI/number0.png"))); // NOI18N

        centenaContLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        centenaContLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Portao/JanelaGUI/number0.png"))); // NOI18N

        dezenaContLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dezenaContLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Portao/JanelaGUI/number0.png"))); // NOI18N

        unidadeContLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unidadeContLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Portao/JanelaGUI/number0.png"))); // NOI18N

        javax.swing.GroupLayout contadorPanelLayout = new javax.swing.GroupLayout(contadorPanel);
        contadorPanel.setLayout(contadorPanelLayout);
        contadorPanelLayout.setHorizontalGroup(
            contadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contadorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(milharContLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(centenaContLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dezenaContLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unidadeContLabel)
                .addGap(14, 14, 14))
        );
        contadorPanelLayout.setVerticalGroup(
            contadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contadorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(milharContLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(centenaContLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dezenaContLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(unidadeContLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        catracaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catracaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Portao/JanelaGUI/gate.png"))); // NOI18N

        entrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Portao/JanelaGUI/entrada.png"))); // NOI18N
        entrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarButtonActionPerformed(evt);
            }
        });
        entrarButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                entrarButtonKeyPressed(evt);
            }
        });

        sairButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Portao/JanelaGUI/saida.png"))); // NOI18N
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        sairButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sairButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout catracaPanelLayout = new javax.swing.GroupLayout(catracaPanel);
        catracaPanel.setLayout(catracaPanelLayout);
        catracaPanelLayout.setHorizontalGroup(
            catracaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catracaPanelLayout.createSequentialGroup()
                .addComponent(catracaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(catracaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        catracaPanelLayout.setVerticalGroup(
            catracaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catracaPanelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(entrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(catracaPanelLayout.createSequentialGroup()
                .addComponent(catracaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout janelaPanelLayout = new javax.swing.GroupLayout(janelaPanel);
        janelaPanel.setLayout(janelaPanelLayout);
        janelaPanelLayout.setHorizontalGroup(
            janelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(catracaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(janelaPanelLayout.createSequentialGroup()
                .addComponent(contadorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        janelaPanelLayout.setVerticalGroup(
            janelaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(janelaPanelLayout.createSequentialGroup()
                .addComponent(contadorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catracaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(janelaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(janelaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrarButtonActionPerformed

    private void entrarButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entrarButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrarButtonKeyPressed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sairButtonActionPerformed

    private void sairButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sairButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sairButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PortaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PortaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PortaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PortaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PortaoGUI portao = new PortaoGUI();
                portao.setTitle("Entrada - by Joamila");
                portao.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel catracaLabel;
    private javax.swing.JPanel catracaPanel;
    private javax.swing.JLabel centenaContLabel;
    private javax.swing.JPanel contadorPanel;
    private javax.swing.JLabel dezenaContLabel;
    private javax.swing.JButton entrarButton;
    private javax.swing.JPanel janelaPanel;
    private javax.swing.JLabel milharContLabel;
    private javax.swing.JButton sairButton;
    private javax.swing.JLabel unidadeContLabel;
    // End of variables declaration//GEN-END:variables
    
    public JLabel getMilharContLabel(){return milharContLabel;}
    public JLabel getCentenaContLabel(){return centenaContLabel;}
    public JLabel getDezenaContLabel(){return dezenaContLabel;}
    public JLabel getUnidadeContLabel(){return unidadeContLabel;}
    public JButton getEntrarButton(){return entrarButton;}
    public JButton getSairButton(){return sairButton;}
    
    public void setMilharContLabel(JLabel milharContLabel){this.milharContLabel = milharContLabel;}
    public void setCentenaContLabel(JLabel centenaContLabel){this.centenaContLabel = centenaContLabel;}
    public void setDezenaContLabel(JLabel dezenaContLabel){this.dezenaContLabel = dezenaContLabel;}
    public void setUnidadeContLabel(JLabel unidadeContLabel){this.unidadeContLabel = unidadeContLabel;}
}
