/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Guarda.JanelaGUI;

import javax.swing.JLabel;
import javax.swing.JSlider;

/**
 *
 * @author Joamila
 * Criado em: 18/04/2016
 * Última atualização em: 20/04/2016
 */
public class GuardaGUI extends javax.swing.JFrame {

    /**
     * Creates new form GuardaGUI
     */
    public GuardaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contAlarmePanel = new javax.swing.JPanel();
        milharLabel = new javax.swing.JLabel();
        centenaLabel = new javax.swing.JLabel();
        dezenaLabel = new javax.swing.JLabel();
        unidadeLabel = new javax.swing.JLabel();
        alarmeLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ajustarModoSlider = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        statusModoLabel = new javax.swing.JLabel();
        statusAlarmeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guarda - by Joamila");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        milharLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        milharLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Portao/JanelaGUI/number0.png"))); // NOI18N

        centenaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        centenaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Portao/JanelaGUI/number0.png"))); // NOI18N

        dezenaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dezenaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Portao/JanelaGUI/number0.png"))); // NOI18N

        unidadeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unidadeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Portao/JanelaGUI/number0.png"))); // NOI18N

        alarmeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout contAlarmePanelLayout = new javax.swing.GroupLayout(contAlarmePanel);
        contAlarmePanel.setLayout(contAlarmePanelLayout);
        contAlarmePanelLayout.setHorizontalGroup(
            contAlarmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contAlarmePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(milharLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centenaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dezenaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alarmeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        contAlarmePanelLayout.setVerticalGroup(
            contAlarmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(milharLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
            .addComponent(centenaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dezenaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(unidadeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(alarmeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ajustarModoSlider.setValue(0);
        ajustarModoSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ajustarModoSliderStateChanged(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guarda/JanelaGUI/noite.png"))); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guarda/JanelaGUI/dia.png"))); // NOI18N

        statusModoLabel.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        statusModoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusModoLabel.setText("Modo Diurno");

        statusAlarmeLabel.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        statusAlarmeLabel.setForeground(new java.awt.Color(255, 0, 0));
        statusAlarmeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusAlarmeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(ajustarModoSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusModoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(statusModoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ajustarModoSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(statusAlarmeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contAlarmePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contAlarmePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajustarModoSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ajustarModoSliderStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ajustarModoSliderStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuardaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuardaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuardaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuardaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                GuardaGUI guarda = new GuardaGUI();
                guarda.setTitle("Guarda - by Joamila");
                guarda.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider ajustarModoSlider;
    private javax.swing.JLabel alarmeLabel;
    private javax.swing.JLabel centenaLabel;
    private javax.swing.JPanel contAlarmePanel;
    private javax.swing.JLabel dezenaLabel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel milharLabel;
    private javax.swing.JLabel statusAlarmeLabel;
    private javax.swing.JLabel statusModoLabel;
    private javax.swing.JLabel unidadeLabel;
    // End of variables declaration//GEN-END:variables

    public JSlider getAjustarModoSlider(){return ajustarModoSlider;}
    public JLabel getAlarmeLabel() {return alarmeLabel;}
    public JLabel getMilharLabel() {return milharLabel;}
    public JLabel getCentenaLabel() {return centenaLabel;}
    public JLabel getDezenaLabel() {return dezenaLabel;}
    public JLabel getUnidadeLabel() {return unidadeLabel;}
    public JLabel getStatusAlarmeLabel() {return statusAlarmeLabel;}
    public JLabel getStatusModoLabel() {return statusModoLabel;}
    
    public void setAjustarModoSlider(JSlider ajustarModoSlider){this.ajustarModoSlider = ajustarModoSlider;}
    public void setAlarmeLabel(JLabel alarmeLabel){this.alarmeLabel = alarmeLabel;}
    public void setMilharLabel(JLabel milharLabel){this.milharLabel = milharLabel;}
    public void setCentenaLabel(JLabel centenaLabel){this.centenaLabel = centenaLabel;}
    public void setDezenaLabel(JLabel dezenaLabel){this.dezenaLabel = dezenaLabel;}
    public void setUnidadeLabel(JLabel unidadeLabel){this.unidadeLabel = unidadeLabel;}
    public void setStatusAlarmeLabel(JLabel statusAlarmeLabel){this.statusAlarmeLabel = statusAlarmeLabel;}
    public void setStatusModoLabel(JLabel statusModoLabel){this.statusModoLabel = statusModoLabel;}
}
