
/**
* AlarmeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmeIDL.idl
* Domingo, 24 de Abril de 2016 19h55min18s GMT-03:00
*/

public final class AlarmeHolder implements org.omg.CORBA.portable.Streamable
{
  public Alarme value = null;

  public AlarmeHolder ()
  {
  }

  public AlarmeHolder (Alarme initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AlarmeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AlarmeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AlarmeHelper.type ();
  }

}
