
/**
* AlarmeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmeIDL.idl
* Domingo, 24 de Abril de 2016 19h55min18s GMT-03:00
*/

public interface AlarmeOperations 
{
  void informarInvasao ();
  boolean verificarInvasao ();
  void iniciarAlarme ();
  void desativarAlarme ();
  boolean verificarAlarme ();
} // interface AlarmeOperations
