
/**
* AlarmePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmeIDL.idl
* Domingo, 24 de Abril de 2016 19h55min18s GMT-03:00
*/

public abstract class AlarmePOA extends org.omg.PortableServer.Servant
 implements AlarmeOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("informarInvasao", new java.lang.Integer (0));
    _methods.put ("verificarInvasao", new java.lang.Integer (1));
    _methods.put ("iniciarAlarme", new java.lang.Integer (2));
    _methods.put ("desativarAlarme", new java.lang.Integer (3));
    _methods.put ("verificarAlarme", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Alarme/informarInvasao
       {
         this.informarInvasao ();
         out = $rh.createReply();
         break;
       }

       case 1:  // Alarme/verificarInvasao
       {
         boolean $result = false;
         $result = this.verificarInvasao ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Alarme/iniciarAlarme
       {
         this.iniciarAlarme ();
         out = $rh.createReply();
         break;
       }

       case 3:  // Alarme/desativarAlarme
       {
         this.desativarAlarme ();
         out = $rh.createReply();
         break;
       }

       case 4:  // Alarme/verificarAlarme
       {
         boolean $result = false;
         $result = this.verificarAlarme ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Alarme:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Alarme _this() 
  {
    return AlarmeHelper.narrow(
    super._this_object());
  }

  public Alarme _this(org.omg.CORBA.ORB orb) 
  {
    return AlarmeHelper.narrow(
    super._this_object(orb));
  }


} // class AlarmePOA
