
/**
* AlarmeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmeIDL.idl
* Domingo, 24 de Abril de 2016 19h55min18s GMT-03:00
*/

abstract public class AlarmeHelper
{
  private static String  _id = "IDL:Alarme:1.0";

  public static void insert (org.omg.CORBA.Any a, Alarme that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Alarme extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AlarmeHelper.id (), "Alarme");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Alarme read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AlarmeStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Alarme value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Alarme narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Alarme)
      return (Alarme)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _AlarmeStub stub = new _AlarmeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Alarme unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Alarme)
      return (Alarme)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _AlarmeStub stub = new _AlarmeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
