
/**
* Alarme.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlarmeIDL.idl
* Domingo, 24 de Abril de 2016 19h55min18s GMT-03:00
*/

public interface Alarme extends AlarmeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Alarme
