
/**
* GuardaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GuardaIDL.idl
* Domingo, 24 de Abril de 2016 19h35min44s GMT-03:00
*/

public abstract class GuardaPOA extends org.omg.PortableServer.Servant
 implements GuardaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("informarMudModo", new java.lang.Integer (0));
    _methods.put ("verificarMudModo", new java.lang.Integer (1));
    _methods.put ("consultarModo", new java.lang.Integer (2));
    _methods.put ("iniciarGuarda", new java.lang.Integer (3));
    _methods.put ("verificarGuarda", new java.lang.Integer (4));
    _methods.put ("desativarGuarda", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Guarda/informarMudModo
       {
         int modo = in.read_long ();
         this.informarMudModo (modo);
         out = $rh.createReply();
         break;
       }

       case 1:  // Guarda/verificarMudModo
       {
         boolean $result = false;
         $result = this.verificarMudModo ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Guarda/consultarModo
       {
         int $result = (int)0;
         $result = this.consultarModo ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // Guarda/iniciarGuarda
       {
         this.iniciarGuarda ();
         out = $rh.createReply();
         break;
       }

       case 4:  // Guarda/verificarGuarda
       {
         boolean $result = false;
         $result = this.verificarGuarda ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // Guarda/desativarGuarda
       {
         this.desativarGuarda ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Guarda:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Guarda _this() 
  {
    return GuardaHelper.narrow(
    super._this_object());
  }

  public Guarda _this(org.omg.CORBA.ORB orb) 
  {
    return GuardaHelper.narrow(
    super._this_object(orb));
  }


} // class GuardaPOA
