
/**
* GuardaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GuardaIDL.idl
* Domingo, 24 de Abril de 2016 19h35min44s GMT-03:00
*/

public interface GuardaOperations 
{
  void informarMudModo (int modo);
  boolean verificarMudModo ();
  int consultarModo ();
  void iniciarGuarda ();
  boolean verificarGuarda ();
  void desativarGuarda ();
} // interface GuardaOperations
