
/**
* Guarda.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GuardaIDL.idl
* Domingo, 24 de Abril de 2016 19h35min44s GMT-03:00
*/

public interface Guarda extends GuardaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Guarda
