
/**
* GuardaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GuardaIDL.idl
* Domingo, 24 de Abril de 2016 19h35min44s GMT-03:00
*/

abstract public class GuardaHelper
{
  private static String  _id = "IDL:Guarda:1.0";

  public static void insert (org.omg.CORBA.Any a, Guarda that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Guarda extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GuardaHelper.id (), "Guarda");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Guarda read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GuardaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Guarda value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Guarda narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Guarda)
      return (Guarda)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _GuardaStub stub = new _GuardaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Guarda unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Guarda)
      return (Guarda)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _GuardaStub stub = new _GuardaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
