
/**
* PortaoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PortaoIDL.idl
* Domingo, 24 de Abril de 2016 18h52min41s GMT-03:00
*/

public interface PortaoOperations 
{
  boolean verificarEntrada ();
  boolean verificarSaida ();
  void registrarEntrada ();
  void registrarSaida ();
  int verificarVisitantes ();
} // interface PortaoOperations
