
/**
* PortaoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PortaoIDL.idl
* Domingo, 24 de Abril de 2016 18h52min41s GMT-03:00
*/

public abstract class PortaoPOA extends org.omg.PortableServer.Servant
 implements PortaoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("verificarEntrada", new java.lang.Integer (0));
    _methods.put ("verificarSaida", new java.lang.Integer (1));
    _methods.put ("registrarEntrada", new java.lang.Integer (2));
    _methods.put ("registrarSaida", new java.lang.Integer (3));
    _methods.put ("verificarVisitantes", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Portao/verificarEntrada
       {
         boolean $result = false;
         $result = this.verificarEntrada ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Portao/verificarSaida
       {
         boolean $result = false;
         $result = this.verificarSaida ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Portao/registrarEntrada
       {
         this.registrarEntrada ();
         out = $rh.createReply();
         break;
       }

       case 3:  // Portao/registrarSaida
       {
         this.registrarSaida ();
         out = $rh.createReply();
         break;
       }

       case 4:  // Portao/verificarVisitantes
       {
         int $result = (int)0;
         $result = this.verificarVisitantes ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Portao:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Portao _this() 
  {
    return PortaoHelper.narrow(
    super._this_object());
  }

  public Portao _this(org.omg.CORBA.ORB orb) 
  {
    return PortaoHelper.narrow(
    super._this_object(orb));
  }


} // class PortaoPOA
